### ISSUE TITLE
Windows 11 Defender identifying compiled exe as a Trojan

### ISSUE THREAD

**Issue by schoenburg** [reconSuave/RollingStoner#3]
Hey, trying to run the exe on a Windows 11 PC and Defender is not having it. It blocks then quarantines the exe file each time saying it detected Trojan:Win32/Wacatac.H!ml.

What would be setting this off?

**Comment by reconSuave** [comment]
Unsigned executables compiled from python files set off the wacatac heuristic, it's just a false positive. You can check the executable on virustotal or another sandbox and see that it doesn't do anything suspicious, or compile your own, then add it to your defender exemptions. I may renew my signing certificate at some point and put a signed one up, which will keep defender from flagging it, but it's several hundred dollars and not worth it just for this project, so best I can do for now.

**Comment by schoenburg** [comment]
Gotcha, thanks for the response!
